### ISSUE TITLE
robustness of docker compose

### ISSUE THREAD

**Issue by marco-solare** [FauxJira/FauxJira#9]
Hey guys, just documenting my first experience with starting 
`docker-compose up`
see log below.

system: 
`os X Catalina (10.15.2)`
docker version: 
`docker -v
Docker version 19.03.5, build 633a0ea`

Expected result:
- containers get built, started up, client is accessible via `http://localhost:8080`

Actual result:

- containers seem to get built without severe errors
- however database seems to shut down itself right after a successful `CREATE DATABASE`:
`waiting for server to shut down...LOG:  received fast shutdown request`
- this seems to be the first thing that has to be resolved to docker-compose the project in my case.
- any ideas on how to tackle that?
- would love to push this thing into "alpha production".
- if we get it there I think it's really worth pushing it forward

```
~/Code/FauxJira (master) # docker-compose up
Creating network "fauxjira_default" with the default driver
Pulling db (postgres:9.6-alpine)...
9.6-alpine: Pulling from library/postgres
c9b1b535fdd9: Pull complete
d1030c456d04: Pull complete
d1d0211bbd9a: Pull complete
e1057c9a2877: Pull complete
3bc0c3206940: Pull complete
93ae0e20a91a: Pull complete
52891a1e2871: Pull complete
6ade8b42d500: Pull complete
aedc566e2fda: Pull complete
Digest: sha256:8ec15b51fd1ec3233ca7bcf3a58e800d863f57c8d07ffdc65fe4640a19f7b2e3
Status: Downloaded newer image for postgres:9.6-alpine
Building api
Step 1/6 : FROM node:lts-alpine
lts-alpine: Pulling from library/node
c9b1b535fdd9: Already exists
750cdd924064: Pull complete
2078ab7cf9df: Pull complete
02f523899354: Pull complete
Digest: sha256:e280e51eaa6e626e4df58a5c1f141e453807c30596179330992c55a0bf4114ca
Status: Downloaded newer image for node:lts-alpine
 ---> afd897e3184b
Step 2/6 : RUN adduser jira-clone --gecos GECOS --shell /bin/bash --disabled-password --home /app
 ---> Running in 9297245601ef
Removing intermediate container 9297245601ef
 ---> dda7a2c74c5f
Step 3/6 : COPY . /app
 ---> 8aab80029cfd
Step 4/6 : WORKDIR /app
 ---> Running in 8bfa43a7d0b2
Removing intermediate container 8bfa43a7d0b2
 ---> f53a70ff1642
Step 5/6 : RUN npm run install-dependencies &&     cp -v /app/docker/entrypoint.sh /usr/bin/entrypoint
 ---> Running in fabb945c509d

> jira_clone@1.0.0 install-dependencies /app
> npm install && cd api && npm install && cd ../client && npm install

npm WARN jira_clone@1.0.0 No repository field.

audited 37 packages in 1.236s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN jira_api@1.0.0 No repository field.

audited 1160 packages in 6.031s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm WARN jira_client@1.0.0 No repository field.

audited 890212 packages in 21.143s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

'/app/docker/entrypoint.sh' -> '/usr/bin/entrypoint'
Removing intermediate container fabb945c509d
 ---> 03bd31a44fe7
Step 6/6 : ENTRYPOINT ["entrypoint"]
 ---> Running in 0ed4d291acaf
Removing intermediate container 0ed4d291acaf
 ---> 2ab61bc81b5f

Successfully built 2ab61bc81b5f
Successfully tagged fauxjira_api:latest
WARNING: Image for service api was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building client
Step 1/6 : FROM node:lts-alpine
 ---> afd897e3184b
Step 2/6 : RUN adduser jira-clone --gecos GECOS --shell /bin/bash --disabled-password --home /app
 ---> Using cache
 ---> dda7a2c74c5f
Step 3/6 : COPY . /app
 ---> Using cache
 ---> 8aab80029cfd
Step 4/6 : WORKDIR /app
 ---> Using cache
 ---> f53a70ff1642
Step 5/6 : RUN npm run install-dependencies &&     cp -v /app/docker/entrypoint.sh /usr/bin/entrypoint
 ---> Using cache
 ---> 03bd31a44fe7
Step 6/6 : ENTRYPOINT ["entrypoint"]
 ---> Using cache
 ---> 2ab61bc81b5f

Successfully built 2ab61bc81b5f
Successfully tagged fauxjira_client:latest
WARNING: Image for service client was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating fauxjira_db_1 ... done
Creating fauxjira_api_1 ... done
Creating fauxjira_client_1 ... done
Attaching to fauxjira_db_1, fauxjira_api_1, fauxjira_client_1
api_1     |
api_1     | > jira_api@1.0.0 start /app/api
api_1     | > nodemon --exec ts-node --files src/index.ts
api_1     |
db_1      | The files belonging to this database system will be owned by user "postgres".
db_1      | This user must also own the server process.
db_1      |
db_1      | The database cluster will be initialized with locale "en_US.utf8".
db_1      | The default database encoding has accordingly been set to "UTF8".
db_1      | The default text search configuration will be set to "english".
db_1      |
db_1      | Data page checksums are disabled.
db_1      |
db_1      | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1      | creating subdirectories ... ok
db_1      | selecting default max_connections ... 100
db_1      | selecting default shared_buffers ... 128MB
db_1      | selecting default timezone ... UTC
db_1      | selecting dynamic shared memory implementation ... posix
db_1      | creating configuration files ... ok
api_1     | [nodemon] 2.0.0
api_1     | [nodemon] to restart at any time, enter `rs`
api_1     | [nodemon] watching dir(s): *.*
api_1     | [nodemon] watching extensions: ts,json
api_1     | [nodemon] starting `ts-node --files src/index.ts`
client_1  |
client_1  | > jira_client@1.0.0 start /app/client
client_1  | > webpack-dev-server
client_1  |
client_1  | ℹ ｢wds｣: Project is running at http://localhost:8080/
client_1  | ℹ ｢wds｣: webpack output is served from /
client_1  | ℹ ｢wds｣: Content not from webpack is served from /app/client/dev
client_1  | ℹ ｢wds｣: 404s will fallback to /index.html
db_1      | running bootstrap script ... ok
db_1      | performing post-bootstrap initialization ... sh: locale: not found
db_1      | No usable system locales were found.
db_1      | Use the option "--debug" to see details.
db_1      | ok
db_1      | syncing data to disk ...
db_1      | WARNING: enabling "trust" authentication for local connections
db_1      | You can change this by editing pg_hba.conf or using the option -A, or
db_1      | --auth-local and --auth-host, the next time you run initdb.
db_1      | ok
db_1      |
db_1      | Success. You can now start the database server using:
db_1      |
db_1      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1      |
db_1      | waiting for server to start....LOG:  database system was shut down at 2020-02-08 20:58:49 UTC
db_1      | LOG:  MultiXact member wraparound protections are now enabled
db_1      | LOG:  database system is ready to accept connections
db_1      | LOG:  autovacuum launcher started
db_1      |  done
db_1      | server started
db_1      | CREATE DATABASE
db_1      |
db_1      |
db_1      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1      |
db_1      | waiting for server to shut down...LOG:  received fast shutdown request
db_1      | LOG:  aborting any active transactions
db_1      | LOG:  autovacuum launcher shutting down
db_1      | LOG:  shutting down
db_1      | .LOG:  database system is shut down
api_1     | Error: connect ECONNREFUSED 172.18.0.2:5432
api_1     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
api_1     |   errno: 'ECONNREFUSED',
api_1     |   code: 'ECONNREFUSED',
api_1     |   syscall: 'connect',
api_1     |   address: '172.18.0.2',
api_1     |   port: 5432
api_1     | }
api_1     | Sat, 08 Feb 2020 20:59:03 GMT body-parser deprecated undefined extended: provide extended option at src/index.ts:38:31
db_1      |  done
db_1      | server stopped
db_1      |
db_1      | PostgreSQL init process complete; ready for start up.
db_1      |
db_1      | LOG:  database system was shut down at 2020-02-08 20:59:02 UTC
db_1      | LOG:  MultiXact member wraparound protections are now enabled
db_1      | LOG:  database system is ready to accept connections
db_1      | LOG:  autovacuum launcher started
client_1  | ℹ ｢wdm｣: Hash: ae2ba5f9eab7f7be42fc
client_1  | Version: webpack 4.41.2
client_1  | Time: 45240ms
client_1  | Built at: 02/08/2020 8:59:13 PM
client_1  |                                  Asset       Size  Chunks             Chunk Names
client_1  | 029c2e0e19032f6cdbef9042552e79fa.woff2   27.4 KiB          [emitted]
client_1  |   162bf4c1112ca598251515bdd76efd60.jpg    551 KiB          [emitted]
client_1  |  1ced22ee6d45bdd05a5383fd9dbd1b43.woff   41.4 KiB          [emitted]
client_1  |  59880bb792378f77deca117ea6b17567.woff   41.3 KiB          [emitted]
client_1  |   6db192ab3ed372d1de19e207a9c46fd6.png   16.4 KiB          [emitted]
client_1  | 94a505bb1e062b41273a8ea77777a3e7.woff2   27.8 KiB          [emitted]
client_1  | 97ca95083f8be0c5d7ee9907cfe28af1.woff2   27.9 KiB          [emitted]
client_1  |  bb9a359afc17edc2c275b4212b8f2fd2.woff   40.8 KiB          [emitted]
client_1  | c8ae3e93ae16983c73a68cf537557de2.woff2   24.4 KiB          [emitted]
client_1  |  ed76eb21560f0dc038cce0adfd65ea3c.woff   33.9 KiB          [emitted]
client_1  |   f3fe29165df0323731ec27695c8d2798.svg   28.9 KiB          [emitted]
client_1  |                            favicon.png   97.3 KiB          [emitted]
client_1  |                             index.html  343 bytes          [emitted]
client_1  |                                main.js   13.3 MiB    main  [emitted]  main
client_1  | Entrypoint main = main.js
client_1  | [0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.jsx 52 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array-buffer.constructor.js] 563 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array-buffer.is-view.js] 404 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array-buffer.slice.js] 1.47 KiB {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.concat.js] 2.34 KiB {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.copy-within.js] 442 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.every.js] 501 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.fill.js] 399 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.filter.js] 847 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.find-index.js] 783 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.find.js] 719 bytes {main} [built]
client_1  | [./node_modules/core-js/modules/es.array.flat-map.js] 803 bytes {main} [built]
client_1  | [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
client_1  | [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
client_1  | [./src/index.jsx] 9.5 KiB {main} [built]
client_1  |     + 983 hidden modules
client_1  | Child html-webpack-plugin for "index.html":
client_1  |      1 asset
client_1  |     Entrypoint undefined = index.html
client_1  |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 447 bytes {0} [built]
client_1  |     [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
client_1  |     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
client_1  |     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
client_1  | ℹ ｢wdm｣: Compiled successfully.

````

**Comment by gharsallahmoez** [comment]
same issue @marco-solare , did u manage to fix it ?
